# Default values for maildev-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

project: maildev

replicaCount: 1

image:
  repository: djfarrelly/maildev
  tag: 1.1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceweb:
  type: LoadBalancer
  port: 80

servicetcp:
  type: LoadBalancer
  port: 25

ingress:
  enabled: true
  annotations: 
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/cluster-issuer: corp-justin-tech-com
  paths: 
    - /
  hosts:
    - mail.corp.justin-tech.com
  tls:
      - hosts:
        - mail.corp.justin-tech.com

extraArgs:
  outgoing-host: smtp.office365.com
  outgoing-port: "587"
  outgoing-user: ""
  outgoing-pass: ""
  verbose: "yes"
  auto-relay: ""
  smtp: "25"
  web: "80"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
